### ISSUE TITLE
Desirability Scale

### ISSUE THREAD

**Issue by etkirsch** [etkirsch/legends-of-erukar#10]
The desirability calculations use a product of the modifier's Desirabilities. This should be a base-2 system. 
- 0.0625 - Horrid, you'd never want this (e.g. Broken)
- 0.125 - Objectively bad (e.g. Wooden or Rusty)
- 0.25 - Probably worse than you would want to use (e.g. Ceramic Weapon)
- 0.5 - Detrimental but may have some good properties to compensate (e,g. Tungsten, Unwieldy)
- 1.0 - Neither bad nor detrimental (e.g. copper, steel, etc)
- 2.0 - Beneficial but may have some bad properties to compensate (e.g. Fine, Bronze, or Swift)
- 4.0 - Objectively good (e.g. Excellent, Silver, or Enhanced)
- 8.0 - So good it's coveted (e.g. Exceptional, Gold, Greater, or Elemental)
- 16.0 - Outstanding, legendary (e.g. Master, Platinum, Grand, or Legendary)

Example values.
- Gold, Fine Rapier: 8.0 x 2.0 x 1.0 = **16.0**
- Broken, Platinum Rapier: 0.0625 x 16.0 x 1.0 = **1.0**
- Enhanced Wooden Sword: 4.0 x 0.125 x 1.0 = **0.5**
- Silver Platemail of Moderate Resolve:  4.0 x 1.0 x 4.0 = **16.0**
- Masterwork Platinum Platemail: 16.0 x 16.0 x 1.0 = **64.0**

As you can see this objectively creates a distribution which reflects the desirability for certain modifiers.

**Comment by etkirsch** [comment]
The biggest question this leads us to is: How can we use a room's calculated danger score to yield more desirable products?

Perhaps what needs to be done is to use the Desirability score and the room's Danger score and calculate a probability that way. This could work well, as we would also need to take the level of the dungeon into consideration.

**Comment by knightbk** [comment]
I think something like this makes sense (if I understand it right)

Use Level first, to generate some items around the level of the current dungeon. 
Then use Danger score to create some matching Desirability items. 
I'm thinking Danger and Desirability should be closely correlated - the more dangerous a room / area is, the more desirable the items should be found (but not always). 
I don't think Level should impact the desirability rating of items, but level should impact danger (so I guess they are A->C correlated in some way.

**Comment by etkirsch** [comment]
I think you're right with the Level. It factors into the calculations before everything, so it has a direct influence on Danger, ergo an indirect influence on Desirability.
