### ISSUE TITLE
Glances/Inspects -- Inventory Modifiers and Materials

### ISSUE THREAD

**Issue by etkirsch** [etkirsch/legends-of-erukar#15]
I've moved Inspect to a new system where Observation objects are used to track what a player can see or sense. Here's a quick rundown of the two stats.

**Acuity** pertains to a character's intellect, mental sharpness, and ability to inspect objects visually through observations.
**Sense** is the character's ability to perceive non-visually (e.g. sounds, intuition, thermoreception, etc); also adjudicates common sense.

When inspecting a room or an object, the character makes two rolls: one for acuity, one for sense. The ranges are [STAT to 50+STAT]. The item takes the highest-met observation and returns it for the player to read. The exemplar values here have not been tweaked, so the numbers are kinda guesswork at the moment but they maintain the notion of higher acuity/sense --> harder to discern.

What I need is for someone to go through the [modifiers](https://github.com/etkirsch/legends-of-erukar/tree/master/erukar/game/modifiers) (inventory modifiers and materials only for the time being) and add basic observations. 

Here's an example of how Observations work, ripped from the [Flaming Weapon](https://github.com/etkirsch/legends-of-erukar/blob/master/erukar/game/modifiers/inventory/random/Flaming.py) modifier.

``` python
    Glances = [
        Observation(acuity=0, sense=0, result='with a fiery {EssentialPart}'),
        Observation(acuity=20, sense=0, result='with flames erupting from the {EssentialPart}')
    ]

    Inspects = [
        Observation(acuity=0, sense=0, result='The {EssentialPart} is on fire.'),
        Observation(acuity=10, sense=0, result='Flames rise off of the {EssentialPart}.'),
        Observation(acuity=10, sense=10, result='Flames rise off of the {EssentialPart}, radiating a large amount of heat through the room..'),
        Observation(acuity=20, sense=0, result='A plume of flames rises from the {EssentialPart}.'),
        Observation(acuity=20, sense=10, result='A plume of flames rises from the {EssentialPart}, radiating a large amount of heat through the room.')
    ]
```

**Glances** are used when inspecting a container or room. Examples:  'In this room you see a sword with a fiery blade.' or 'In the chest you see a shield made of an unholy red stone.'

**Inspects** are used when inspecting a specific item. Example:  'The head of this axe is made of a milky white metal which has a bluish sheen.'

---

Inside of braces (e.g. `{alias}` --> `self.alias()` and `{EssentialPart}` --> `self.EssentialPart`) are method calls or parameters which are evaluated at runtime. If there is a vertical pipe (e.g. `{alias|lifeform}` --> `self.lifeform.alias()`), the element on the right is what is chosen as the target for the method call or parameter to be pulled into the string.

**Note**: If necessary, I can add more to the targeting for mutation (`{alias|chest|lifeform}` --> `self.lifeform.chest.alias()`}, but it is not currently supported.

**Comment by etkirsch** [comment]
If you see something like the following 

```python
    BriefDescription = "{EssentialPart} is broken."
    AbsoluteMinimalDescription = "The {EssentialPart} has been broken."
    VisualMinimalDescription = "The {EssentialPart} has been broken."
    VisualIdealDescription = "The {EssentialPart} has been broken."
    SensoryMinimalDescription = ""
    SensoryIdealDescription = ""
    DetailedMinimalDescription = "The {EssentialPart} has been broken."
    DetailedIdealDescription = "The {EssentialPart} has been broken."
    Adjective = ""
```

...you can remove this. This is from the old system.

**Comment by etkirsch** [comment]
You will also need to make sure that the import `erukar.engine.model.Observation import Observation` is at the very top of the file

**Comment by knightbk** [comment]
I can take a look at this stuff this weekend possibly.
